services:
  grpcalc-dev:
    container_name: grpcdemo-server-dev
    image: grpcdemo-server-dev 
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    develop:
      watch:
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./go.mod
    profiles:
      - development
      - default

  grpcalc-prod:
    container_name: grpcdemo-server-prod
    image: grpdemo-server-prod
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    profiles:
      - production

  grpcui:
    container_name: grpcui
    image: wongnai/grpcui
    ports:
      - "8081:8080"
    environment:
      - GRPCUI_SERVER=grpcdemo-server-dev:8080  # Fix: Use the container name, not localhost
    depends_on:
      - grpcalc-dev
    restart: unless-stopped
    profiles:
      - development
      - default
